const industries = [
  {
    name: "Automobile",
    id: "Automobile",
    hash: "automobile",
    description:
      "We develop documents that fulfill automobile industry specific requirements and support the products delivered. Our expert technical writers have good domain experience and develop quality documents, which aid in improving design and development, control of monitoring and measuring devices, product and process training.",
    serviceProvided: [
      "Software Engineering Services",
      "Technical Writing",
      "Document Migration",
      "Content Strategy",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/arch.jpg",
    backColor: "#fdeced",
    darkColor: "#cd5c5c",
    iClass: "fa-solid fa-car",
  },
  {
    name: "Education",
    id: "Education",
    hash: "education",
    description:
      "The field of education is witnessing massive change, new styles, and modes of education are evolving and we can help you to keep pace with the emerging trends in creating interactive training manual. We believe in using the technology to support learning that can be interactive, easy to interpret and convey the right learning methods to students. Our writers are well-versed with the principles and approaches of instructional design and use latest technological processes and resources to facilitate learning.",
    serviceProvided: [
      "Product Development",
      "Knowledge Base Management",
      "Content Writing",
      "Editing and proofreading",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/edu.jpg",
    backColor: "#eafdf3",
    darkColor: "#086d38",
    iClass: "fa-solid fa-graduation-cap",
  },
  {
    name: "Healthcare",
    id: "Healthcare",
    hash: "health-care",
    description:
      "Healthcare documentation requires knowledge of medical terminology, healthcare standards, and documentation requirements. We can provide documentation services in the healthcare domain and develop good quality documents, which aid in ongoing clinical decision-making, continuity of care, and risk management.",
    serviceProvided: [
      "Technical Writing",
      "Mobile Application Development",
      "Software Development",
      "Structured Authoring",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/health.jpg",
    backColor: "#f3f5fc",
    darkColor: "#324da0",
    iClass: "fa-solid fa-briefcase-medical",
  },
  {
    name: "Defense",
    id: "Defense",
    hash: "defense",
    description: `Metapercept is one of the few companies in India that provides technical writing services for Defense domain. We follow S1000D standard and controlled English for technical documentation projects. We offer in-depth competence in meeting the requirements for high-quality technical documentation for the defense industry. We can help you plan any Defense project documentation by following Military Standard, Military Specification (often colloquially called "MIL-STD","MIL-SPEC", or "MilSpecs") to achieve standardization objectives.`,
    serviceProvided: [
      "Information Architecture",
      "Software Development",
      "Content Strategy",
      "DITA Implementation",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/def.jpg",
    backColor: "#fef7f1",
    darkColor: "#f47f20",
    iClass: "fa-solid fa-shield-halved",
  },
  {
    name: "Aerospace",
    id: "Aerospace",
    hash: "aerospace",
    description:
      "We are experts at producing technical documents for aerospace industry. We have specialized technical documentation staff having experience in aerospace domain and expsoure to ATA and AECMA standards that are required to develop the documents for fulfilling requirements of procurement, integration and obsolescence management. We have considerable experience and expertise in ASD S1000D, ASD Simplified Technical English (STE), and other related standards and implementations.",
    serviceProvided: [
      "Translation and Localization",
      "Structured Authoring",
      "Software Development",
      "Technical Writing",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/aero.jpg",
    backColor: "#fff9ea",
    darkColor: "#fcb713",
    iClass: "fa-solid fa-rocket",
  },
  {
    name: "Oil & Energy",
    id: "OilEnergy",
    hash: "oil-energy",
    description:
      "The Oil and Energy industry’s safety and regulatory requirements, global supply-chain setup, diversified set of stakeholders and need to access technical documents that are handy for the field engineers, interactive, portable and provides real time inputs are always of high importance.",
    serviceProvided: [
      "Software engineering services",
      "Technical Writing",
      "Document Migration",
      "Content Strategy",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/oil.jpg",
    backColor: "#fdeced",
    darkColor: "#cd5c5c",
    iClass: "fa-solid fa-fire-flame-simple",
  },
  {
    name: "IT Hardware",
    id: "ITHardware",
    hash: "it-hardware",
    description:
      "A well-written technical manual for hardware products has the potential of becoming selling point for any product. Hardware products and appliances for IT/Software products must have clear procedure based technical documents so that end-users can easily install, assemble, or operate that product. Not only such documents increase usability of the product, but also lowers down the support cost. We have expertise in developing technical manuals such as Install Guide, Operator Manual, Product Assembly Manual, and Maintenance Manual.",
    serviceProvided: [
      "Software Engineering Services",
      "Product Documentation",
      "Template Design",
      "Content Strategy",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/hardware.jpg",
    backColor: "#eafdf3",
    darkColor: "#086d38",
    iClass: "fa-solid fa-microchip",
  },
  {
    name: "Heavy Engineering",
    id: "HeavyEngineering",
    hash: "heavy-engineering",
    description:
      "Metapercept has right technical communication skills to produce high quality technical documents. Our expert Technical Writers have domain experience and thus, have the ability to understand customer requirements, processes, and tools. Our technical writing services and solutions help our customers meet the stringent technical publication requirement and provide good quality technical documents such as maintenance manuals and repair manuals.",
    serviceProvided: [
      "Information Architecture",
      "Software Development",
      "Content Strategy",
      "DITA Implementation",
    ],
    link: "/industries",
    img: "/assets/img/about-us/industries/heav.jpg",
    backColor: "#f3f5fc",
    darkColor: "#324da0",
    iClass: "fa-solid fa-book",
  },
];

export default industries;
