const portfolio_data_three = [
  {
    id: 1,
    img: "/assets/img/about-us/business-partner/OxygenLogo.png",
    name: "Syncro Soft SRL",
    description:
      "Syncro Soft is a software company founded in 1998 with a large area of expertise in XML technologies and ..",
    url: "https://www.oxygenxml.com/",
    title: "UX, Website Design",
    cls: "design consultancy",
    delay: ".5s",
    category: "Content Management System, Authoring Tool Partner",
    filter_id: ["all", "design", "business", "consultancy", "support"],
    backColor: "rgb(255,116,82)",
  },
  {
    id: 2,
    img: "/assets/img/about-us/business-partner/ditatooLogo.png",
    name: "DITAToo",
    description:
      "DITAToo is a Content Management System (DITA CMS) that automates and facilitates many of the tasks relate..",
    url: "https://www.ditatoo.com/",
    title: "UX, Website Design",
    cls: "business support",
    delay: ".5s",
    category: "Content Management System",
    filter_id: ["all", "design", "business", "consultancy", "support"],
    backColor: "rgb(180 217 119)",
  },
  {
    id: 3,
    img: "/assets/img/about-us/business-partner/adobetcLogo.png",
    name: "Adobe Systems",
    description:
      "Adobe Systems – Adobe is the global leader in digital marketing and digital media solutions...",
    url: "https://www.adobe.com/",
    title: "Adobe Systems",
    cls: "consultancy business",
    delay: ".5s",
    category: "Authoring Tool Partner, Content Management System",
    filter_id: ["design", "business", "consultancy", "support"],
    backColor: "rgb(249,156,219)",
  },
  {
    id: 4,
    img: "/assets/img/about-us/business-partner/AWS-Partner.png",
    name: "Amazon Web Services",
    description:
      "Metapercept is strategically partnered with the AWS through the global partner program for technology and..",
    url: "https://aws.amazon.com/",
    title: "UX, Website Design",
    cls: "design support",
    delay: ".5s",
    category: "DevOps",
    filter_id: ["all", "design", "business", "consultancy", "support"],
    backColor: "rgb(255,196,0)",
  },
  {
    id: 5,
    img: "/assets/img/about-us/business-partner/HerettoLogo.png",
    name: "Heretto",
    description:
      "Heretto is a SaaS content operations platform designed to create, manage, and personalize enterprise know..",
    url: "https://heretto.com/",
    title: "UX, Website Design",
    cls: "design support",
    delay: ".5s",
    category: "Content Management System",
    filter_id: ["all", "design", "business", "consultancy", "support"],
    backColor: "rgb(0,199,229)",
  },
  {
    id: 6,
    img: "/assets/img/about-us/business-partner/altovaLogo.png",
    name: "Altova",
    description:
      "Altova® is a software company specializing in tools that assist developers with data management, software..",
    url: "https://www.altova.com/",
    title: "UX, Website Design",
    cls: "design support",
    delay: ".5s",
    category: "Content Management System",
    filter_id: ["all", "design", "business", "consultancy", "support"],
    backColor: "#116082",
  },
  {
    id: 7,
    img: "/assets/img/about-us/business-partner/Google-Cloud-Logo.png",
    name: "Google Cloud Platform",
    description:
      "Whether your business is early in its journey or well on its way to digital transformation, Google Cloud can..",
    url: "https://cloud.google.com/",
    title: "UX, Website Design",
    cls: "design support",
    delay: ".5s",
    category: "DevOps",
    filter_id: ["all", "design", "business", "consultancy", "support"],
    backColor: "rgb(87,217,163)",
  },
];
export default portfolio_data_three;
