import Head from "next/head";

const SEO = ({ pageTitle, keywords = "artificial intelligence" }) => (
  <>
    <Head>
      <title>{pageTitle && `${pageTitle}`}</title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <meta name="keywords" content={keywords} />
      <link rel="shortcut icon" href="/favicon.ico" />
      {/* <meta name="robots" content="noindex, follow" /> */}
    </Head>
  </>
);

export default SEO;
